#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.{build}.0

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Install-Module -Name 'Pester' -SkipPublisherCheck -Force
        Invoke-Pester

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
  - ps: |
      # No deploy task configured yet
